version: '3'
services:

  # rooms:
  #   build: 
  #     context: .
  #     dockerfile: ./apps/rooms/Dockerfile
  #     target: development
  #   command: npm run start:dev auth
  #   env_file:
  #     - ./apps/rooms/.env
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/src/app
  # auth:
  #   build: 
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #     target: development
  #   command: npm run start:dev auth
  #   env_file:
  #     - ./apps/auth/.env
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - .:/usr/src/app

  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  mongo_data:
