export const PriceData = [
  {
    baserate: 100,
    tax: 18,
    room_name: 'Standard Room',
    discount: 0,
    season_price: 0.6,
    late_booking: 0.4,
    early_booking: -0.3,
    long_booking: -0.15,
  },
  {
    baserate: 140,
    tax: 18,
    room_name: 'Deluxe Room',
    discount: 0,
    season_price: 0.6,
    late_booking: 0.4,
    early_booking: -0.3,
    long_booking: -0.15,
  },
  {
    baserate: 200,
    tax: 18,
    room_name: 'Suite',
    season_price: 0.5,
    discount: 0,
    early_booking: -0.25,
    late_booking: 0.45,
    long_booking: -0.2,
  },

  {
    baserate: 320,
    tax: 18,
    room_name: 'Penthouse',
    season_price: 0.8,
    discount: 0,
    early_booking: -0.2,
    late_booking: 0.3,
    long_booking: -0.15,
  },
  {
    baserate: 450,
    tax: 18,
    room_name: 'Beachfront Villa',
    season_price: 0.8,
    discount: 0,
    early_booking: -0.2,
    late_booking: 0.3,
    long_booking: -0.15,
  },
];
